services:
  mysql:
    image: mysql:8.0
    container_name: sistema_tienda_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 9029
      MYSQL_DATABASE: sistema_tienda_db
      MYSQL_USER: asako
      MYSQL_PASSWORD: 9029
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql_data: